CREATE TABLE [dbo].[ROLES] (
    [ID]   NVARCHAR (50) NOT NULL,
    [ROLE] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IX_ROLES] UNIQUE NONCLUSTERED ([ROLE] ASC)
);