CREATE TABLE [dbo].[USERS] (
    [ID]       NVARCHAR (50) NOT NULL,
    [USERNAME] NVARCHAR (50) NOT NULL,
    [PASSWORD] NVARCHAR (50) NOT NULL,
    [EMAIL]    NVARCHAR (50) NOT NULL,
    [NAME] NVARCHAR(50) NULL, 
    [REGISTRATION_DATE] DATETIME NULL, 
    CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [IX_USERS] UNIQUE NONCLUSTERED ([USERNAME] ASC),
    CONSTRAINT [IX_USERS_1] UNIQUE NONCLUSTERED ([EMAIL] ASC)
);

