CREATE TABLE [dbo].[USER_ROLES]
(
	[USER_ID] NVARCHAR(50) NOT NULL , 
    [ROLE_ID] NVARCHAR(50) NOT NULL, 
    PRIMARY KEY ([USER_ID], [ROLE_ID])
)

GO
ALTER TABLE dbo.USER_ROLES ADD CONSTRAINT
	FK_USER_ROLES_USERS FOREIGN KEY
	(
	USER_ID
	) REFERENCES dbo.USERS
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE
GO
ALTER TABLE dbo.USER_ROLES ADD CONSTRAINT
	FK_USER_ROLES_ROLES FOREIGN KEY
	(
	ROLE_ID
	) REFERENCES dbo.ROLES
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION